networks:
  backend:
    name: backend
    external: true

services:
  auth_api:
    container_name: auth_api
    image: auth_api
    build:
      context: .
      dockerfile: API/AuthApp.API/Development.Dockerfile
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend